variable "resource_name" {
  description = "The name of the SAML provider"
  type        = string
}

variable "saml_metadata_document" {
  description = "An XML metadata document generated by the identity provider"
  type        = string
}

variable "common_tags" {
  description = "Common tags"
  type        = map(string)
  default     = {}
}
